import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';

const SUBTYPE_PLAIN: Record<string, string> = {
  'Luminal A': 'Most common — typically slower-growing and hormone-sensitive',
  'Luminal B': 'Hormone-sensitive but tends to grow faster than Luminal A',
  'HER2': 'Tests positive for HER2 protein — targeted therapies available',
  'Triple Negative': 'Negative for three receptors — typically treated with chemotherapy',
};

const DOCTOR_QUESTIONS: Record<string, string[]> = {
  'Luminal A': [
    'Is hormone therapy (tamoxifen or an aromatase inhibitor) appropriate for me?',
    'How often should I have follow-up scans or blood tests?',
    'Is chemotherapy recommended in my specific case?',
    'What lifestyle changes may reduce recurrence risk?',
    'Is genetic testing (BRCA1/2) recommended for my family?',
  ],
  'Luminal B': [
    'Should I have a genomic test (e.g. Oncotype DX) to guide treatment decisions?',
    'Is targeted therapy such as a CDK4/6 inhibitor appropriate for me?',
    'How does my Ki-67 score affect treatment planning?',
    'What is the expected timeline for hormone therapy?',
    'Can I receive fertility-preserving treatment before starting therapy?',
  ],
  'HER2': [
    'Am I eligible for trastuzumab (Herceptin) or pertuzumab-based therapy?',
    'What is the role of neoadjuvant (pre-surgery) therapy in my case?',
    'What cardiac monitoring is required during HER2-targeted therapy?',
    'Is T-DM1 an option if standard therapy does not work?',
    'What clinical trials are available for HER2-positive breast cancer?',
  ],
  'Triple Negative': [
    'Is immunotherapy (e.g. pembrolizumab) appropriate given my PD-L1 status?',
    'Should I be tested for BRCA1/2 mutations to consider PARP inhibitors?',
    'What chemotherapy regimen is recommended as first-line treatment?',
    'What is the role of surgery versus chemotherapy first in my case?',
    'Are there clinical trials specifically for triple-negative breast cancer?',
  ],
};

const DISCLAIMER =
  'This PDF is generated by an educational AI tool. The AI was trained across 3 hospitals ' +
  'without sharing patient records. This is NOT a clinical diagnosis. Only a certified ' +
  'oncologist can diagnose cancer. If you have concerns, contact your doctor or nearest cancer centre immediately.';

@Injectable()
export class PdfService {
  async generate(caseData: {
    id: string;
    predictedSubtype: string;
    confidence: number;
    modelVersion: number;
    createdAt: Date;
  }): Promise<Buffer> {
    const subtype = caseData.predictedSubtype;
    const confidenceLabel =
      caseData.confidence >= 0.7 ? 'High' : caseData.confidence >= 0.5 ? 'Moderate' : 'Low';
    const questions = DOCTOR_QUESTIONS[subtype] ?? [];
    const plain = SUBTYPE_PLAIN[subtype] ?? subtype;
    const dateStr = new Date(caseData.createdAt).toLocaleDateString('en-GB', {
      day: 'numeric', month: 'long', year: 'numeric',
    });

    return new Promise<Buffer>((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks: Buffer[] = [];
      doc.on('data', (c: Buffer) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const TEAL = '#14b8a6';
      const DARK = '#0d1117';
      const GREY = '#8b949e';

      // Logo placeholder
      doc.roundedRect(50, 50, 80, 28, 4).fillColor('#1c2128').fill();
      doc.fontSize(10).fillColor(TEAL).font('Helvetica-Bold').text('FedMRI', 56, 60);

      // Header
      doc.moveDown(0.5);
      doc.fontSize(18).fillColor(DARK).font('Helvetica-Bold')
        .text('AI Scan Summary', 50, 96);
      doc.fontSize(9).fillColor(GREY).font('Helvetica')
        .text(`Generated ${dateStr}  •  Case ${caseData.id.slice(0, 8)}  •  Model v${caseData.modelVersion}`, 50, 116);

      doc.moveTo(50, 136).lineTo(545, 136).strokeColor('#e2e8f0').lineWidth(0.5).stroke();

      // Section 1: AI Result
      doc.moveDown(1.5);
      doc.fontSize(11).fillColor(TEAL).font('Helvetica-Bold').text('AI Result', 50);
      doc.moveDown(0.4);
      doc.fontSize(20).fillColor(DARK).font('Helvetica-Bold').text(subtype);
      doc.fontSize(10).fillColor(GREY).font('Helvetica').text(`Confidence: ${confidenceLabel}`);

      // Section 2: What this means
      doc.moveDown(1);
      doc.fontSize(11).fillColor(TEAL).font('Helvetica-Bold').text('What this means');
      doc.moveDown(0.4);
      doc.fontSize(10).fillColor(DARK).font('Helvetica').text(plain, { lineGap: 4 });

      // Section 3: Questions for your doctor
      doc.moveDown(1);
      doc.fontSize(11).fillColor(TEAL).font('Helvetica-Bold').text('Questions to ask your doctor');
      doc.moveDown(0.4);
      questions.forEach((q, i) => {
        doc.fontSize(10).fillColor(DARK).font('Helvetica')
          .text(`${i + 1}.  ${q}`, { lineGap: 3 });
      });

      // Disclaimer footer
      const footerY = doc.page.height - 90;
      doc.moveTo(50, footerY).lineTo(545, footerY).strokeColor('#e2e8f0').lineWidth(0.5).stroke();
      doc.fontSize(8).fillColor('#fb7185').font('Helvetica')
        .text(DISCLAIMER, 50, footerY + 10, { width: 495, lineGap: 2, align: 'left' });

      doc.end();
    });
  }
}
