import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';

const SUBTYPE_PLAIN: Record<string, string> = {
  'Luminal A': 'Most common — typically slower-growing and hormone-sensitive',
  'Luminal B': 'Hormone-sensitive but tends to grow faster than Luminal A',
  HER2: 'Tests positive for HER2 protein — targeted therapies available',
  'Triple Negative': 'Negative for three receptors — typically treated with chemotherapy',
  Luminal:
    'Hormone-receptor positive — these cancers usually respond to hormone (endocrine) therapy',
  'Non-Luminal':
    'Less likely to be hormone-driven — your care team will advise the most suitable treatment path',
};

// Patient-facing accent per subtype (mirrors the app palette).
const SUBTYPE_COLOR: Record<string, string> = {
  'Luminal A': '#14b8a6',
  Luminal: '#14b8a6',
  'Luminal B': '#2563eb',
  HER2: '#f59e0b',
  'Triple Negative': '#fb7185',
  'Non-Luminal': '#f59e0b',
};

// Generic, reassuring next-steps every patient report includes.
const NEXT_STEPS = [
  'Book a follow-up with your oncologist or breast-care team to review this scan.',
  'Bring this summary and your original imaging to the appointment.',
  'Ask which additional tests (e.g. biopsy / IHC) confirm the subtype.',
  'Note any new symptoms and questions before your visit.',
];

const DOCTOR_QUESTIONS: Record<string, string[]> = {
  'Luminal A': [
    'Is hormone therapy (tamoxifen or an aromatase inhibitor) appropriate for me?',
    'How often should I have follow-up scans or blood tests?',
    'Is chemotherapy recommended in my specific case?',
    'What lifestyle changes may reduce recurrence risk?',
    'Is genetic testing (BRCA1/2) recommended for my family?',
  ],
  'Luminal B': [
    'Should I have a genomic test (e.g. Oncotype DX) to guide treatment decisions?',
    'Is targeted therapy such as a CDK4/6 inhibitor appropriate for me?',
    'How does my Ki-67 score affect treatment planning?',
    'What is the expected timeline for hormone therapy?',
    'Can I receive fertility-preserving treatment before starting therapy?',
  ],
  HER2: [
    'Am I eligible for trastuzumab (Herceptin) or pertuzumab-based therapy?',
    'What is the role of neoadjuvant (pre-surgery) therapy in my case?',
    'What cardiac monitoring is required during HER2-targeted therapy?',
    'Is T-DM1 an option if standard therapy does not work?',
    'What clinical trials are available for HER2-positive breast cancer?',
  ],
  'Triple Negative': [
    'Is immunotherapy (e.g. pembrolizumab) appropriate given my PD-L1 status?',
    'Should I be tested for BRCA1/2 mutations to consider PARP inhibitors?',
    'What chemotherapy regimen is recommended as first-line treatment?',
    'What is the role of surgery versus chemotherapy first in my case?',
    'Are there clinical trials specifically for triple-negative breast cancer?',
  ],
  Luminal: [
    'Is hormone (endocrine) therapy the right treatment for me?',
    'Do I also need chemotherapy, or is hormone therapy enough?',
    'Would a genomic test help decide my treatment?',
    'How often will I need follow-up scans?',
    'Is genetic testing (BRCA1/2) recommended for my family?',
  ],
  'Non-Luminal': [
    'Which treatments are most effective for a non-hormone-driven cancer?',
    'Should I be tested for HER2 status or BRCA1/2 mutations?',
    'Is chemotherapy or immunotherapy recommended in my case?',
    'What is the role of surgery in my treatment plan?',
    'Are there clinical trials I could consider?',
  ],
};

const DISCLAIMER =
  'This summary is generated by an educational AI tool. The AI was trained across 3 hospitals ' +
  'without sharing any patient records. This is NOT a clinical diagnosis. Only a certified ' +
  'oncologist can diagnose cancer. If you have any concerns, contact your doctor or nearest ' +
  'cancer centre immediately.';

// Layout constants (A4, 50pt margins → 495pt content width).
const M = 50;
const RIGHT = 545;
const W = RIGHT - M; // 495
const TEAL = '#0d9488';
const INK = '#0f172a';
const GREY = '#64748b';
const LIGHT = '#e2e8f0';
const TRACK = '#eef2f6';

@Injectable()
export class PdfService {
  async generate(caseData: {
    id: string;
    predictedSubtype: string;
    confidence: number;
    modelVersion: number;
    createdAt: Date;
    probs?: unknown;
    subjectLabel?: string | null;
  }): Promise<Buffer> {
    const subtype = caseData.predictedSubtype;
    const accent = SUBTYPE_COLOR[subtype] ?? TEAL;
    const confPct = Math.round((caseData.confidence ?? 0) * 100);
    const confidenceLabel =
      caseData.confidence >= 0.7 ? 'High' : caseData.confidence >= 0.5 ? 'Moderate' : 'Low';
    const questions = DOCTOR_QUESTIONS[subtype] ?? [];
    const plain = SUBTYPE_PLAIN[subtype] ?? subtype;
    const dateStr = new Date(caseData.createdAt).toLocaleDateString('en-GB', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
    });

    // Probability rows (binary vs 4-class), normalised to [{label, p}].
    const probs = Array.isArray(caseData.probs)
      ? (caseData.probs as number[])
      : [];
    const probLabels =
      probs.length === 4
        ? ['Luminal A', 'Luminal B', 'HER2', 'Triple Negative']
        : ['Luminal', 'Non-Luminal'];
    const probRows = probLabels
      .map((label, i) => ({ label, p: probs[i] ?? 0 }))
      .filter((r) => probs.length > 0);

    return new Promise<Buffer>((resolve, reject) => {
      const doc = new PDFDocument({ margin: M, size: 'A4' });
      const chunks: Buffer[] = [];
      doc.on('data', (c: Buffer) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // ── Section heading helper ──────────────────────────────────────────
      const heading = (text: string) => {
        doc.moveDown(1.1);
        const y = doc.y;
        doc.rect(M, y + 1, 3, 11).fill(accent);
        doc
          .fontSize(11)
          .fillColor(TEAL)
          .font('Helvetica-Bold')
          .text(text.toUpperCase(), M + 10, y, { characterSpacing: 0.5 });
        doc.moveDown(0.5);
      };

      // ── Header band ─────────────────────────────────────────────────────
      doc.rect(0, 0, doc.page.width, 92).fill('#0d1117');
      doc
        .roundedRect(M, 30, 86, 30, 5)
        .fillColor('#161b22')
        .fill();
      doc
        .fontSize(13)
        .fillColor('#2dd4bf')
        .font('Helvetica-Bold')
        .text('FedMRI', M + 12, 39);
      doc
        .fontSize(17)
        .fillColor('#ffffff')
        .font('Helvetica-Bold')
        .text('Your AI Scan Summary', M + 110, 33, { width: W - 110, align: 'right' });
      doc
        .fontSize(8.5)
        .fillColor('#8b949e')
        .font('Helvetica')
        .text(
          `Generated ${dateStr}   •   Case ${caseData.id.slice(0, 8)}   •   Model v${caseData.modelVersion}`,
          M + 110,
          56,
          { width: W - 110, align: 'right' },
        );

      // ── Result hero card ────────────────────────────────────────────────
      const heroY = 112;
      doc
        .roundedRect(M, heroY, W, 92, 8)
        .fillColor('#f8fafc')
        .fill()
        .lineWidth(1)
        .strokeColor(accent)
        .stroke();
      // accent rail
      doc.roundedRect(M, heroY, 6, 92, 3).fill(accent);

      doc
        .fontSize(9)
        .fillColor(GREY)
        .font('Helvetica-Bold')
        .text('AI-PREDICTED SUBTYPE', M + 22, heroY + 16, { characterSpacing: 0.5 });
      doc
        .fontSize(26)
        .fillColor(INK)
        .font('Helvetica-Bold')
        .text(subtype, M + 22, heroY + 30);
      doc
        .fontSize(9.5)
        .fillColor(GREY)
        .font('Helvetica')
        .text(plain, M + 22, heroY + 62, { width: W - 200 });

      // Confidence chip (right side of hero)
      const chipW = 150;
      const chipX = RIGHT - chipW - 16;
      doc
        .roundedRect(chipX, heroY + 18, chipW, 56, 6)
        .fillColor('#ffffff')
        .fill()
        .lineWidth(1)
        .strokeColor(LIGHT)
        .stroke();
      doc
        .fontSize(8)
        .fillColor(GREY)
        .font('Helvetica-Bold')
        .text('CONFIDENCE', chipX, heroY + 28, { width: chipW, align: 'center' });
      doc
        .fontSize(22)
        .fillColor(accent)
        .font('Helvetica-Bold')
        .text(`${confPct}%`, chipX, heroY + 40, { width: chipW, align: 'center' });
      doc
        .fontSize(8.5)
        .fillColor(GREY)
        .font('Helvetica')
        .text(`${confidenceLabel} confidence`, chipX, heroY + 62, {
          width: chipW,
          align: 'center',
        });

      doc.y = heroY + 104;

      // ── Probability breakdown ───────────────────────────────────────────
      if (probRows.length > 0) {
        heading('Prediction breakdown');
        let by = doc.y + 2;
        const labelW = 110;
        const valW = 42;
        const trackX = M + labelW;
        const trackW = W - labelW - valW;
        for (const row of probRows) {
          const isTop = row.label === subtype;
          const rowColor = SUBTYPE_COLOR[row.label] ?? GREY;
          const pct = Math.round(row.p * 100);
          doc
            .fontSize(9.5)
            .fillColor(isTop ? INK : GREY)
            .font(isTop ? 'Helvetica-Bold' : 'Helvetica')
            .text(row.label, M, by + 1, { width: labelW - 6 });
          doc.roundedRect(trackX, by, trackW, 9, 4.5).fill(TRACK);
          if (pct > 0) {
            doc
              .roundedRect(trackX, by, Math.max((trackW * pct) / 100, 4), 9, 4.5)
              .fill(isTop ? rowColor : '#cbd5e1');
          }
          doc
            .fontSize(9)
            .fillColor(isTop ? INK : GREY)
            .font('Helvetica-Bold')
            .text(`${pct}%`, RIGHT - valW, by + 1, { width: valW, align: 'right' });
          by += 20;
        }
        doc.y = by;
      }

      // ── What this means ─────────────────────────────────────────────────
      heading('What this means for you');
      doc
        .fontSize(10)
        .fillColor(INK)
        .font('Helvetica')
        .text(
          `Your scan was analysed by an AI model and most closely matches the "${subtype}" subtype. ${plain}. ` +
            `This is a screening aid to help your conversation with your doctor — it is not a final diagnosis.`,
          M,
          doc.y + 2,
          { width: W, lineGap: 3, align: 'left' },
        );

      // ── What happens next ───────────────────────────────────────────────
      heading('What happens next');
      NEXT_STEPS.forEach((s, i) => {
        const y = doc.y + 2;
        doc.circle(M + 4, y + 5, 2.2).fill(accent);
        doc
          .fontSize(10)
          .fillColor(INK)
          .font('Helvetica')
          .text(s, M + 14, y, { width: W - 14, lineGap: 2 });
        if (i < NEXT_STEPS.length - 1) doc.moveDown(0.2);
      });

      // ── Questions for your doctor ───────────────────────────────────────
      if (questions.length > 0) {
        heading('Questions to ask your doctor');
        questions.forEach((q, i) => {
          doc
            .fontSize(10)
            .fillColor(INK)
            .font('Helvetica')
            .text(`${i + 1}.  ${q}`, M, doc.y + 2, { width: W, lineGap: 2 });
        });
      }

      // ── Privacy reassurance box ─────────────────────────────────────────
      doc.moveDown(1.1);
      const pY = doc.y;
      doc
        .roundedRect(M, pY, W, 46, 6)
        .fillColor('#ecfdf5')
        .fill()
        .lineWidth(1)
        .strokeColor('#99f6e4')
        .stroke();
      doc
        .fontSize(9.5)
        .fillColor(TEAL)
        .font('Helvetica-Bold')
        .text('Your privacy is protected', M + 14, pY + 10);
      doc
        .fontSize(8.5)
        .fillColor('#0f766e')
        .font('Helvetica')
        .text(
          'This AI was trained across 3 hospitals without your scan or records ever leaving the clinic — ' +
            '0 bytes of your personal data were shared to produce this result.',
          M + 14,
          pY + 24,
          { width: W - 28, lineGap: 1.5 },
        );

      // ── Disclaimer footer ───────────────────────────────────────────────
      // Anchored high enough that the 3-line disclaimer clears the 50pt bottom
      // margin — otherwise pdfkit auto-paginates the last line onto a blank page.
      const footerY = doc.page.height - 108;
      doc
        .moveTo(M, footerY)
        .lineTo(RIGHT, footerY)
        .strokeColor(LIGHT)
        .lineWidth(0.5)
        .stroke();
      doc
        .fontSize(7.5)
        .fillColor('#b91c1c')
        .font('Helvetica')
        .text(DISCLAIMER, M, footerY + 8, { width: W, lineGap: 1.5, align: 'left' });

      doc.end();
    });
  }
}
