"""
inference_service.py
====================
FastAPI inference service serving the FedSCRT model for the web application.

Receives an uploaded DCE-MRI volume (.mha or .nii.gz), preprocesses it exactly
as during training, runs the FedSCRT model, and returns a binary molecular
subtype prediction (Luminal vs Non-Luminal) with calibrated probabilities.

The interactive OpenAPI documentation is auto-generated by FastAPI and served
at /docs (Swagger UI) and /redoc (ReDoc).

Endpoints:
    POST /predict      → predict subtype from an uploaded volume
    GET  /health       → liveness / model-loaded check
    GET  /model-info   → model metadata and validation metrics

Privacy:
    Inference is performed locally on the server. No raw patient data is
    transmitted to any external service.

Pipeline position:
    save_fedscrt_model.py (fedscrt_final.pt) → THIS MODULE → web frontend

Run:
    uvicorn inference_service:app --host 0.0.0.0 --port 8001

Authors:  TALEB Youcef & BENSEFIA Yazid — USTHB Bioinformatics 2026
Supervisor: Mme Malika MEHDI-SILHADI
Dataset:  737 DCE-MRI volumes, DOI: 10.5281/zenodo.7956360
"""

import os, sys, io, torch, numpy as np
os.environ.setdefault("MRI_NUM_CLASSES", "2")   # binary mode before config import
sys.path.insert(0, ".")

from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional
import tempfile, pathlib

# ── Application setup ─────────────────────────────────────────────────────────
app = FastAPI(
    title="FedSCRT Inference Service",
    version="1.0.0",
    description="Binary breast MRI molecular subtype classification "
                "(Luminal vs Non-Luminal) using a Federated SCAFFOLD + "
                "Classifier Retraining (FedSCRT) model.",
)

# Permissive CORS: the web frontend may be served from a different origin/port
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

DEVICE     = torch.device("cuda" if torch.cuda.is_available() else "cpu")
MODEL      = None   # loaded once at startup (see load_model)
MODEL_META = {}     # model metadata dict (arch, metrics, label map)

def load_model():
    """
    Load the FedSCRT checkpoint into the global MODEL and populate MODEL_META.

    Called once on FastAPI startup. Reads checkpoints/fedscrt_final.pt, builds a
    ConvNeXt-MIL model, loads the weights, and switches to eval mode.
    """
    global MODEL, MODEL_META
    from main import build_model
    ck   = torch.load("checkpoints/fedscrt_final.pt", map_location=DEVICE)
    MODEL = build_model("convnext_mil", DEVICE)
    MODEL.load_state_dict(ck["model_state"], strict=False)
    MODEL.eval()
    MODEL_META = {
        "arch":       ck.get("arch", "convnext_mil"),
        "task":       ck.get("task", "binary"),
        "f1":         ck.get("f1", 0.6289),
        "auc":        ck.get("auc", 0.6874),
        "label_map":  ck.get("label_map", {0: "Luminal", 1: "Non-Luminal"}),
        "fedscrt":    ck.get("fedscrt", True),
    }
    print(f"Model loaded on {DEVICE} | F1={MODEL_META['f1']:.4f}")

@app.on_event("startup")
async def startup():
    """FastAPI startup hook: load the model into memory before serving requests."""
    load_model()

# ── Response Schemas (OpenAPI models) ─────────────────────────────────────────
class PredictionResponse(BaseModel):
    """Schema for the /predict response body (rendered in /docs)."""
    prediction:        str           # "Luminal" or "Non-Luminal"
    confidence:        float         # probability of the predicted class
    luminal_prob:      float         # P(Luminal)
    non_luminal_prob:  float         # P(Non-Luminal)
    model_f1:          float         # model's validation macro F1
    model_auc:         float         # model's validation AUC-ROC
    device:            str           # "cuda" or "cpu"

class HealthResponse(BaseModel):
    """Schema for the /health response body."""
    status: str            # "ok" when the service is responsive
    model_loaded: bool     # True once the model is loaded into memory

# ── Preprocessing ─────────────────────────────────────────────────────────────
def preprocess_volume(mha_path: str) -> torch.Tensor:
    """
    Load and preprocess a volume exactly as during training.

    Applies the same preprocess_raw pipeline (normalize → crop → resize to
    64×128×128), then replicates each slice to 3 channels and resizes to 224×224
    to match the backbone's expected input.

    Args:
        mha_path (str): Path to the uploaded .mha / .nii.gz file.

    Returns:
        torch.Tensor: Shape (64, 3, 224, 224) — 64 RGB slices ready for the model.
    """
    from image_process import preprocess_raw   # shared preprocessing pipeline
    vol = preprocess_raw(mha_path)             # → (64, 128, 128) float32
    vol = torch.from_numpy(vol).float()        # (64, H, W)

    # Replicate each grey slice to 3 channels and resize to 224×224
    import torch.nn.functional as F
    slices = []
    for s in vol:
        s = s.unsqueeze(0).unsqueeze(0)        # (H, W) → (1, 1, H, W)
        s = F.interpolate(s, size=(224, 224), mode="bilinear", align_corners=False)
        s = s.repeat(1, 3, 1, 1)               # (1, 1, 224, 224) → (1, 3, 224, 224)
        slices.append(s)
    return torch.cat(slices, dim=0)            # (64, 3, 224, 224)

# ── Prediction Endpoint ───────────────────────────────────────────────────────
@app.post("/predict", response_model=PredictionResponse)
async def predict(file: UploadFile = File(...)):
    """
    Predict the binary molecular subtype from an uploaded MRI volume.

    Accepts a multipart file upload (.mha or .nii.gz), preprocesses it, runs the
    FedSCRT model, and returns the predicted subtype with class probabilities.

    Args:
        file (UploadFile): The uploaded MRI volume file.

    Returns:
        PredictionResponse: Prediction label, confidence, per-class probabilities,
            and the model's validation metrics.

    Raises:
        HTTPException: 503 if the model is not loaded.
    """
    if MODEL is None:
        raise HTTPException(status_code=503, detail="Model not loaded")

    # save upload to temp file
    suffix = pathlib.Path(file.filename).suffix or ".mha"
    with tempfile.NamedTemporaryFile(suffix=suffix, delete=False) as tmp:
        tmp.write(await file.read())
        tmp_path = tmp.name

    try:
        # preprocess
        slices = preprocess_volume(tmp_path).to(DEVICE)  # (64, 3, 224, 224)
        slices = slices.unsqueeze(0)                      # (1, 64, 3, 224, 224)

        # inference
        with torch.no_grad():
            logits = MODEL(slices)                        # (1, 2)
            probs  = torch.softmax(logits, dim=-1)[0]    # (2,)

        luminal_prob     = float(probs[0].cpu())
        non_luminal_prob = float(probs[1].cpu())
        pred_class       = 0 if luminal_prob > non_luminal_prob else 1
        prediction       = MODEL_META["label_map"][str(pred_class)]
        confidence       = max(luminal_prob, non_luminal_prob)

        return PredictionResponse(
            prediction=prediction,
            confidence=round(confidence, 4),
            luminal_prob=round(luminal_prob, 4),
            non_luminal_prob=round(non_luminal_prob, 4),
            model_f1=MODEL_META["f1"],
            model_auc=MODEL_META["auc"],
            device=str(DEVICE),
        )

    finally:
        os.unlink(tmp_path)

@app.get("/health", response_model=HealthResponse)
async def health():
    """
    Health check endpoint.

    Returns:
        HealthResponse: status "ok" and whether the model is loaded.
    """
    return HealthResponse(status="ok", model_loaded=MODEL is not None)

@app.get("/model-info")
async def model_info():
    """
    Return model metadata and validation performance for the frontend.

    Returns:
        dict: Architecture, task description, validation metrics, privacy note,
            device, and class label descriptions.
    """
    return {
        "model":        "FedSCRT",
        "architecture": "ConvNeXt-Nano + GatedAttentionMIL",
        "task":         "Binary breast MRI subtype (Luminal vs Non-Luminal)",
        "validation":   {"macro_f1": 0.6289, "auc_roc": 0.6874, "accuracy": 0.7027},
        "training":     "Federated Classifier Retraining (FedSCRT)",
        "privacy":      "Raw data never transmitted — model weights only",
        "device":       str(DEVICE),
        "classes":      {0: "Luminal (hormone therapy eligible)", 1: "Non-Luminal"},
    }
